' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace K12_Manager
	
	Public Class frmoauth_jwt
		
		Private ad As MySqlDataAdapter
		
		Private Sub frmoauth_jwt_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
            Dim strConn As String = "port=3306;server=us-cdbr-iron-east-01.cleardb.net;user id=bf1c9d658ff1ed;password=3175e2fb;database=ad_5b8045e5aae6ad9;"
            ad = New MySqlDataAdapter("select * from `oauth_jwt`", strConn)
            Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
            ad.Fill(Me.newDataSet.oauth_jwt)
            ad.DeleteCommand = builder.GetDeleteCommand()
            ad.UpdateCommand = builder.GetUpdateCommand()
            ad.InsertCommand = builder.GetInsertCommand()
            BindingNavigatorAddNewItem.Enabled = True
            BindingNavigatorCountItem.Enabled = True
            BindingNavigatorDeleteItem.Enabled = True
            BindingNavigatorMoveFirstItem.Enabled = True
            BindingNavigatorMovePreviousItem.Enabled = True
            BindingNavigatorPositionItem.Enabled = True
            BindingNavigatorMoveNextItem.Enabled = True
            BindingNavigatorMoveLastItem.Enabled = True
            ToolStripButton1.Enabled = True
            dataGridView1.AutoGenerateColumns = False
            Dim strConn2 As String = "port=3306;server=us-cdbr-iron-east-01.cleardb.net;user id=bf1c9d658ff1ed;password=3175e2fb;database=ad_5b8045e5aae6ad9;"
			Dim ad2 As MySql.Data.MySqlClient.MySqlDataAdapter = Nothing
			Dim colclient_id As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colclient_id.DataPropertyName = "client_id"
			colclient_id.HeaderText = "client_id"
			colclient_id.Name = "colclient_id"
			dataGridView1.Columns.Add(colclient_id)
			Dim colsubject As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colsubject.DataPropertyName = "subject"
			colsubject.HeaderText = "subject"
			colsubject.Name = "colsubject"
			dataGridView1.Columns.Add(colsubject)
			Dim colpublic_key As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colpublic_key.DataPropertyName = "public_key"
			colpublic_key.HeaderText = "public_key"
			colpublic_key.Name = "colpublic_key"
			dataGridView1.Columns.Add(colpublic_key)
			Me.dataGridView1.DataSource = Me.oauth_jwtBindingSource
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			oauth_jwtBindingSource.EndEdit()
			ad.Update(Me.newDataSet.oauth_jwt)
		End Sub
		
		Private Sub frmoauth_jwt_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
		Private Sub dataGridView1_CellValidating(sender As Object, e As DataGridViewCellValidatingEventArgs)
			
			Dim row As DataGridViewRow= dataGridView1.Rows(e.RowIndex)
			Dim value As Object = e.FormattedValue
			e.Cancel = False
			row.ErrorText = ""
			If row.IsNewRow Then
				Return
			End If
			If e.ColumnIndex = 0 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field client_id is required"
					Return
				End If
			End If
			If e.ColumnIndex = 1 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field subject is required"
					Return
				End If
			End If
			If e.ColumnIndex = 2 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field public_key is required"
					Return
				End If
			End If
		End Sub
		Private Sub dataGridView1_DataError(ByVal sender As Object, ByVal e As DataGridViewDataErrorEventArgs)
			dataGridView1.Rows(e.RowIndex).ErrorText = e.Exception.Message
			e.Cancel = true
		End Sub
		
		Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs)
			oauth_jwtBindingSource.AddNew()
		End Sub
		
	End Class
	
End Namespace
