' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Imports System.ComponentModel
Imports MySql.Data.MySqlClient

Namespace K12_Manager
	
	Public Class frmmessages
		
		Private ad As MySqlDataAdapter
		
		Private Sub frmmessages_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
            Dim strConn As String = "port=3306;server=us-cdbr-iron-east-01.cleardb.net;user id=bf1c9d658ff1ed;password=3175e2fb;database=ad_5b8045e5aae6ad9;"
            ad = New MySqlDataAdapter("select * from `messages`", strConn)
            Dim builder As MySqlCommandBuilder = New MySqlCommandBuilder(ad)
            ad.Fill(Me.newDataSet.messages)
            ad.DeleteCommand = builder.GetDeleteCommand()
            ad.UpdateCommand = builder.GetUpdateCommand()
            ad.InsertCommand = builder.GetInsertCommand()
            BindingNavigatorAddNewItem.Enabled = False
            BindingNavigatorCountItem.Enabled = False
            BindingNavigatorDeleteItem.Enabled = False
            BindingNavigatorMoveFirstItem.Enabled = False
            BindingNavigatorMovePreviousItem.Enabled = False
            BindingNavigatorPositionItem.Enabled = False
            BindingNavigatorMoveNextItem.Enabled = False
            BindingNavigatorMoveLastItem.Enabled = False
            ToolStripButton1.Enabled = True
            dataGridView1.AutoGenerateColumns = False
            Dim strConn2 As String = "port=3306;server=us-cdbr-iron-east-01.cleardb.net;user id=bf1c9d658ff1ed;password=3175e2fb;database=ad_5b8045e5aae6ad9;"
			Dim ad2 As MySql.Data.MySqlClient.MySqlDataAdapter = Nothing
			Dim colid As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colid.DataPropertyName = "id"
			colid.HeaderText = "id"
			colid.Name = "colid"
			dataGridView1.Columns.Add(colid)
			Dim colmitt As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colmitt.DataPropertyName = "mitt"
			colmitt.HeaderText = "mitt"
			colmitt.Name = "colmitt"
			dataGridView1.Columns.Add(colmitt)
			Dim coldest As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			coldest.DataPropertyName = "dest"
			coldest.HeaderText = "dest"
			coldest.Name = "coldest"
			dataGridView1.Columns.Add(coldest)
			Dim coldate As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			coldate.DataPropertyName = "date"
			coldate.HeaderText = "date"
			coldate.Name = "coldate"
			dataGridView1.Columns.Add(coldate)
			Dim coltime As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			coltime.DataPropertyName = "time"
			coltime.HeaderText = "time"
			coltime.Name = "coltime"
			dataGridView1.Columns.Add(coltime)
			Dim colmsg As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn()
			colmsg.DataPropertyName = "msg"
			colmsg.HeaderText = "msg"
			colmsg.Name = "colmsg"
			dataGridView1.Columns.Add(colmsg)
			Me.dataGridView1.DataSource = Me.messagesBindingSource
		End Sub
		
		Private Sub ToolStripButton1_Click(sender As System.Object, e As System.EventArgs) Handles ToolStripButton1.Click
			If Not Me.Validate() Then
				Return
			End If
			messagesBindingSource.EndEdit()
			ad.Update(Me.newDataSet.messages)
		End Sub
		
		Private Sub frmmessages_FormClosing(sender As System.Object, e As System.Windows.Forms.FormClosingEventArgs) Handles MyBase.FormClosing
			e.Cancel = False
		End Sub
		
		Private Sub dataGridView1_CellValidating(sender As Object, e As DataGridViewCellValidatingEventArgs)
			
			Dim s As String
			Dim row As DataGridViewRow= dataGridView1.Rows(e.RowIndex)
			Dim value As Object = e.FormattedValue
			e.Cancel = False
			row.ErrorText = ""
			If row.IsNewRow Then
				Return
			End If
			If e.ColumnIndex = 0 Then
				
				Dim v as Integer
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field id is required"
					Return
				End If
				s = value.ToString()
				If Not Integer.TryParse( s, v ) Then
					e.Cancel = True
					row.ErrorText = "The field id must be Integer."
					Return
				End If
			End If
			If e.ColumnIndex = 1 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field mitt is required"
					Return
				End If
			End If
			If e.ColumnIndex = 2 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field dest is required"
					Return
				End If
			End If
			If e.ColumnIndex = 3 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field date is required"
					Return
				End If
			End If
			If e.ColumnIndex = 4 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field time is required"
					Return
				End If
			End If
			If e.ColumnIndex = 5 Then
				
				If (TypeOf value is DBNull) OrElse String.IsNullOrEmpty( value.ToString() ) Then 
					e.Cancel = True
					row.ErrorText = "The field msg is required"
					Return
				End If
			End If
		End Sub
		Private Sub dataGridView1_DataError(ByVal sender As Object, ByVal e As DataGridViewDataErrorEventArgs)
			dataGridView1.Rows(e.RowIndex).ErrorText = e.Exception.Message
			e.Cancel = true
		End Sub
		
		Private Sub bindingNavigatorAddNewItem_Click(sender As System.Object, e As System.EventArgs)
			messagesBindingSource.AddNew()
		End Sub
		
	End Class
	
End Namespace
