' ++++++++++++++++++++++++++++++++++++++++++++++++++
' This code is generated by a tool and is provided "as is", without warranty of any kind,
' express or implied, including but not limited to the warranties of merchantability,
' fitness for a particular purpose and non-infringement.
' In no event shall the authors or copyright holders be liable for any claim, damages or
' other liability, whether in an action of contract, tort or otherwise, arising from,
' out of or in connection with the software or the use or other dealings in the software.
' ++++++++++++++++++++++++++++++++++++++++++++++++++
' 

Namespace K12_Manager

<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmMain
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.MenuStrip1 = New System.Windows.Forms.MenuStrip()
        Me.FormsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmmessagesToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmoauth_access_tokensToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmoauth_authorization_codesToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmoauth_clientsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmoauth_jwtToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmoauth_refresh_tokensToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmoauth_usersToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmquestionnairesToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmquestionsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmquestions_questionnairesToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmtopicsToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.frmuserToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
            Me.MenuStrip1.SuspendLayout()
            Me.SuspendLayout()
            '
            'MenuStrip1
            '
            Me.MenuStrip1.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.FormsToolStripMenuItem})
            Me.MenuStrip1.Location = New System.Drawing.Point(0, 0)
            Me.MenuStrip1.Name = "MenuStrip1"
            Me.MenuStrip1.Size = New System.Drawing.Size(284, 24)
            Me.MenuStrip1.TabIndex = 0
            Me.MenuStrip1.Text = "MenuStrip1"
            '
            'FormsToolStripMenuItem
            '
            Me.FormsToolStripMenuItem.DropDownItems.AddRange(New System.Windows.Forms.ToolStripItem() {Me.frmmessagesToolStripMenuItem, Me.frmoauth_access_tokensToolStripMenuItem, Me.frmoauth_authorization_codesToolStripMenuItem, Me.frmoauth_clientsToolStripMenuItem, Me.frmoauth_jwtToolStripMenuItem, Me.frmoauth_refresh_tokensToolStripMenuItem, Me.frmoauth_usersToolStripMenuItem, Me.frmquestionnairesToolStripMenuItem, Me.frmquestionsToolStripMenuItem, Me.frmquestions_questionnairesToolStripMenuItem, Me.frmtopicsToolStripMenuItem, Me.frmuserToolStripMenuItem})
            Me.FormsToolStripMenuItem.Name = "FormsToolStripMenuItem"
            Me.FormsToolStripMenuItem.Size = New System.Drawing.Size(52, 20)
            Me.FormsToolStripMenuItem.Text = "Forms"
            '
            'frmmessagesToolStripMenuItem
            '
            Me.frmmessagesToolStripMenuItem.Name = "frmmessagesToolStripMenuItem"
            Me.frmmessagesToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmmessagesToolStripMenuItem.Text = "messages"
            '
            'frmoauth_access_tokensToolStripMenuItem
            '
            Me.frmoauth_access_tokensToolStripMenuItem.Name = "frmoauth_access_tokensToolStripMenuItem"
            Me.frmoauth_access_tokensToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmoauth_access_tokensToolStripMenuItem.Text = "oauth_access_tokens"
            '
            'frmoauth_authorization_codesToolStripMenuItem
            '
            Me.frmoauth_authorization_codesToolStripMenuItem.Name = "frmoauth_authorization_codesToolStripMenuItem"
            Me.frmoauth_authorization_codesToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmoauth_authorization_codesToolStripMenuItem.Text = "oauth_authorization_codes"
            '
            'frmoauth_clientsToolStripMenuItem
            '
            Me.frmoauth_clientsToolStripMenuItem.Name = "frmoauth_clientsToolStripMenuItem"
            Me.frmoauth_clientsToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmoauth_clientsToolStripMenuItem.Text = "oauth_clients"
            '
            'frmoauth_jwtToolStripMenuItem
            '
            Me.frmoauth_jwtToolStripMenuItem.Name = "frmoauth_jwtToolStripMenuItem"
            Me.frmoauth_jwtToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmoauth_jwtToolStripMenuItem.Text = "oauth_jwt"
            '
            'frmoauth_refresh_tokensToolStripMenuItem
            '
            Me.frmoauth_refresh_tokensToolStripMenuItem.Name = "frmoauth_refresh_tokensToolStripMenuItem"
            Me.frmoauth_refresh_tokensToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmoauth_refresh_tokensToolStripMenuItem.Text = "oauth_refresh_tokens"
            '
            'frmoauth_usersToolStripMenuItem
            '
            Me.frmoauth_usersToolStripMenuItem.Name = "frmoauth_usersToolStripMenuItem"
            Me.frmoauth_usersToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmoauth_usersToolStripMenuItem.Text = "oauth_users"
            '
            'frmquestionnairesToolStripMenuItem
            '
            Me.frmquestionnairesToolStripMenuItem.Name = "frmquestionnairesToolStripMenuItem"
            Me.frmquestionnairesToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmquestionnairesToolStripMenuItem.Text = "questionnaires"
            '
            'frmquestionsToolStripMenuItem
            '
            Me.frmquestionsToolStripMenuItem.Name = "frmquestionsToolStripMenuItem"
            Me.frmquestionsToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmquestionsToolStripMenuItem.Text = "questions"
            '
            'frmquestions_questionnairesToolStripMenuItem
            '
            Me.frmquestions_questionnairesToolStripMenuItem.Name = "frmquestions_questionnairesToolStripMenuItem"
            Me.frmquestions_questionnairesToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmquestions_questionnairesToolStripMenuItem.Text = "questions_questionnaires"
            '
            'frmtopicsToolStripMenuItem
            '
            Me.frmtopicsToolStripMenuItem.Name = "frmtopicsToolStripMenuItem"
            Me.frmtopicsToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmtopicsToolStripMenuItem.Text = "topics"
            '
            'frmuserToolStripMenuItem
            '
            Me.frmuserToolStripMenuItem.Name = "frmuserToolStripMenuItem"
            Me.frmuserToolStripMenuItem.Size = New System.Drawing.Size(216, 22)
            Me.frmuserToolStripMenuItem.Text = "user"
            '
            'frmMain
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(284, 261)
            Me.Controls.Add(Me.MenuStrip1)
            Me.MainMenuStrip = Me.MenuStrip1
            Me.Name = "frmMain"
            Me.Text = "Main Form"
            Me.MenuStrip1.ResumeLayout(False)
            Me.MenuStrip1.PerformLayout()
            Me.ResumeLayout(False)
            Me.PerformLayout()

        End Sub
    Friend WithEvents MenuStrip1 As System.Windows.Forms.MenuStrip
    Friend WithEvents FormsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmmessagesToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmoauth_access_tokensToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmoauth_authorization_codesToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmoauth_clientsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmoauth_jwtToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmoauth_refresh_tokensToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmoauth_usersToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmquestionnairesToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmquestionsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmquestions_questionnairesToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmtopicsToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents frmuserToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem

End Class
End Namespace
